# Site settings
title: PHP
email: sangulo@coppel.com
description: > # this means to ignore newlines until "baseurl:"
  Sitio dedicado a la recopilación de las mejores prácticas y estandares
  para PHP.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost" # the base hostname & protocol for your site
twitter_username:
github_username:
exclude: [Gemfile, Gemfile.lock, Procfile]
encoding: utf-8

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
